### ISSUE TITLE
Adding the card again

### ISSUE THREAD

**Issue by FaisalBiyari** [kormax/apple-device-as-access-card#1]
I succeeded in adding the card to my Apple Watch.
I was originally presented with the option of iPhone & Apple Watch, but the phone failed to add it, requiring me to change my passcode.

I have the card on my Apple Watch, and I would like to add it to my iPhone, or old Apple Watch.
I cannot find an option to add the card to Apple Wallet (Although I can find it under NFC Mini-App, under My Cards)

Is there a way to add it, or do I need to top up again for each device I add it to?

**Comment by kormax** [comment]
If you open the "Watch" app, tap on the "Wallet" submenu and click on the card, there will be an "Add card to iPhone" button.

Moreover, if you just remove the card from the watch, it will appear in "previous cards" section when adding it back on any of your devices.

**Comment by FaisalBiyari** [comment]
I found the option in both scenarios you suggested.

When trying to add it to the iPhone, through either option, it seems the card will be "Moved" and not duplicated else where.

Meaning that if I want to mass produce this in my location, I'm looking at an estimated cost of $1.5 USD per card. (Minimum 10 yuan card balance)

Does this seem correct to you?

(No that I am complaining. I'm just glad we found a solution that allows us to add iOS/WatchOS to the devices that can gain access without anything like jailbreak)

Also
Can this be optimized?
Is there a validity period for the cards? (Do they vanish after 30 days of no use?)

**Comment by kormax** [comment]
Card validity period is decided by the issuer. I don't know it.

But the cards I already have are about 1.5 years old, and expiration date in-app says 2028, so seems like a lot.

As for price, some cards can be bought for 5CNY, but you have to search for it.

Also, you cannot duplicate the card between two devices because most transit cards act as a source of truth, with balance being actually on the card, and not in some database.
